model_reasoning_effort = "high"
hide_agent_reasoning = true
network_access = true
approval_mode = "full-auto"  # suggest | auto-edit | full-auto

notify = [
  "powershell.exe",
  "-Command",
  "Add-Type -AssemblyName presentationCore; [System.Windows.Forms.SystemSounds]::Exclamation.Play()"
]

[tools]
web_search = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]
